# Generated by Django 4.2.2 on 2023-07-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='serial_number',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
