# Generated by Django 3.2 on 2022-02-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowed',
            options={'verbose_name_plural': 'Borrowed'},
        ),
        migrations.AddField(
            model_name='borrowed',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
