# Generated by Django 3.2 on 2022-02-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_main', '0002_auto_20220227_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
