# Generated by Django 3.2 on 2022-02-27 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_main', '0003_alter_borrowed_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowed',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Borrowed'},
        ),
    ]
